apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-04-04T05:50:54Z"
    generation: 4
    labels:
      app: flask-paruvi
    name: flask-paruvi
    namespace: default
    resourceVersion: "22996"
    uid: 39d1ff90-c297-4643-8648-81211c5c182c
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: flask-paruvi
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: flask-paruvi
      spec:
        containers:
        - image: arun0692/flask-app:v1
          imagePullPolicy: IfNotPresent
          name: flask-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2025-04-04T05:50:54Z"
      lastUpdateTime: "2025-04-04T05:51:03Z"
      message: ReplicaSet "flask-paruvi-589bc4c96b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-04-04T06:03:46Z"
      lastUpdateTime: "2025-04-04T06:03:46Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 4
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
