---
- name: Apply baseline configuration to all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Configure web servers
  hosts: webservers
  become: true
  roles:
    - webserver
  vars_files:
    - ../group_vars/webservers.yml
    - ../vault/secrets.yml 