---
all:
  children:
    linux_servers:
      hosts:
        prod-linux-01:
          ansible_host: 192.168.2.101
          ansible_user: ansible
        prod-linux-02:
          ansible_host: 192.168.2.102
          ansible_user: ansible
    windows_servers:
      hosts:
        prod-win-01:
          ansible_host: 192.168.2.103
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_winrm_transport: basic
    webservers:
      hosts:
        prod-linux-01:
        prod-linux-02: 