---
- name: Configure common settings for all servers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache (Ubuntu)
      apt:
        update_cache: "{{ update_cache }}"
      when: ansible_os_family == "Debian"

    - name: Update all packages (Ubuntu)
      apt:
        upgrade: "{{ update_packages }}"
      when: ansible_os_family == "Debian"

    - name: Update dnf cache (RedHat)
      dnf:
        update_cache: "{{ update_cache }}"
      when: ansible_os_family == "RedHat"

    - name: Update all packages (RedHat)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Configure NTP
      template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
      notify: restart ntp

    - name: Install fail2ban
      package:
        name: fail2ban
        state: present
      when: fail2ban_enabled | bool

    - name: Configure fail2ban
      template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify: restart fail2ban
      when: fail2ban_enabled | bool

    - name: Install UFW
      package:
        name: ufw
        state: present
      when: ufw_enabled | bool

    - name: Configure UFW
      ufw:
        rule: allow
        port: "{{ item }}"
      loop: "{{ allowed_ports }}"
      when: ufw_enabled | bool

  handlers:
    - name: restart ntp
      service:
        name: ntp
        state: restarted

    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted
      when: fail2ban_enabled | bool 