---
all:
  children:
    linux_servers:
      hosts:
        dev-linux-01:
          ansible_host: 192.168.1.101
          ansible_user: ansible
        dev-linux-02:
          ansible_host: 192.168.1.102
          ansible_user: ansible
    windows_servers:
      hosts:
        dev-win-01:
          ansible_host: 192.168.1.103
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_winrm_transport: basic
    webservers:
      hosts:
        dev-linux-01:
        dev-linux-02: 